//! Golden integration tests against the real F1 IR pack (BluePill class).
//! Requires `data/stm32f1.irpack` (generated by the importer); tests skip
//! when absent so CI without the pack still passes the unit suite.

use std::path::PathBuf;
use stm32ck_engine::config::ConfigDoc;
use stm32ck_engine::diag::has_errors;
use stm32ck_engine::session::validate;
use stm32ck_ir::model::IrPack;

fn load_pack(name: &str) -> Option<IrPack> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("data")
        .join(name);
    if !path.is_file() {
        eprintln!("skip: {} not present (run the importer first)", path.display());
        return None;
    }
    let compressed = std::fs::read(path).unwrap();
    let bin = zstd::decode_all(compressed.as_slice()).unwrap();
    Some(postcard::from_bytes(&bin).unwrap())
}

fn golden_doc() -> ConfigDoc {
    serde_json::from_str(
        r#"{
          "schemaVersion": 1,
          "mcu": { "part": "STM32F103C8Tx" },
          "clock": {
            "sources": { "HSE": { "kind": "crystal", "freqHz": 8000000 } },
            "targets": { "SYSCLK": { "hz": 72000000 } }
          },
          "peripherals": {
            "USART1": {
              "mode": "Asynchronous",
              "params": { "BaudRate": 115200 },
              "pins": { "TX": "PA9", "RX": "PA10" },
              "nvic": { "enabled": true, "preemptionPriority": 1 }
            }
          },
          "gpio": { "PC13": { "mode": "output", "initHigh": true, "label": "LED" } }
        }"#,
    )
    .unwrap()
}

#[test]
fn f103_bluepill_72mhz_usart() {
    let Some(pack) = load_pack("stm32f1.irpack") else { return };
    let doc = golden_doc();
    let resolved = validate(&pack, &doc).expect("hard failure");

    for d in &resolved.diags {
        eprintln!("diag: {:?} {} {} {}", d.severity, d.code, d.path, d.message);
    }
    assert!(!has_errors(&resolved.diags), "golden config must be clean");

    // Clock: solver must reach exactly 72 MHz via PLL (HSE 8 * 9).
    let sysclk = resolved
        .clock
        .freqs
        .iter()
        .find(|(id, _)| id.contains("SysCLK") || id.to_uppercase().contains("SYSCLK"))
        .map(|(_, f)| *f)
        .expect("sysclk propagated");
    assert_eq!(sysclk, stm32ck_ir::expr::Num::from_integer(72_000_000));
    assert_eq!(
        resolved.clock.assignments.get("PLLMUL").map(String::as_str),
        Some("RCC_PLL_MUL9"),
        "assignments: {:?}",
        resolved.clock.assignments
    );
    // APB1 must be divided to <= 36 MHz.
    let apb1 = resolved
        .clock
        .freqs
        .get("APB1Output")
        .copied()
        .expect("apb1 propagated");
    assert!(apb1 <= stm32ck_ir::expr::Num::from_integer(36_000_000));
    // Flash latency for 72 MHz is 2 WS on F1.
    assert_eq!(
        resolved.clock.derived.get("FLatency").map(String::as_str),
        Some("FLASH_LATENCY_2"),
        "derived: {:?}",
        resolved.clock.derived
    );

    // Pinout: TX on PA9, RX on PA10, default remap (no AFIO macro).
    let tx = resolved
        .pin_plan
        .placements
        .iter()
        .find(|p| p.signal == "USART1_TX")
        .expect("TX placed");
    assert_eq!(tx.pin, "PA9");
    assert!(resolved.pin_plan.remaps.is_empty(), "default remap expected");

    // Params: USART1 resolved with our baud + defaults for the rest.
    let usart = resolved
        .periphs
        .iter()
        .find(|p| p.instance == "USART1")
        .unwrap();
    assert_eq!(usart.hal_mode.as_deref(), Some("UART"));
    assert_eq!(usart.params.get("BaudRate").map(String::as_str), Some("115200"));
    assert!(usart.params.contains_key("WordLength"), "params: {:?}", usart.params);
    assert!(usart.config_for_mode.iter().any(|c| c == "Uart_Init"));

    // NVIC: USART1_IRQn resolved.
    assert!(resolved.nvic.iter().any(|i| i.irqn == "USART1_IRQn"));
}

#[test]
fn f103_remap_to_pb6_pb7() {
    let Some(pack) = load_pack("stm32f1.irpack") else { return };
    let mut doc = golden_doc();
    let usart = doc.peripherals.get_mut("USART1").unwrap();
    usart.pins.insert("TX".into(), "PB6".into());
    usart.pins.insert("RX".into(), "PB7".into());
    let resolved = validate(&pack, &doc).expect("hard failure");
    for d in &resolved.diags {
        eprintln!("diag: {:?} {} {} {}", d.severity, d.code, d.path, d.message);
    }
    assert!(!has_errors(&resolved.diags));
    let tx = resolved
        .pin_plan
        .placements
        .iter()
        .find(|p| p.signal == "USART1_TX")
        .unwrap();
    assert_eq!(tx.pin, "PB6");
    assert_eq!(
        resolved.pin_plan.remaps.get("USART1").map(String::as_str),
        Some("USART1_REMAP1"),
        "remap group must move with the pins"
    );
    assert_eq!(
        tx.af_macro.as_deref(),
        Some("__HAL_AFIO_REMAP_USART1_ENABLE")
    );
}

#[test]
fn f103_rejects_sysclk_beyond_max() {
    let Some(pack) = load_pack("stm32f1.irpack") else { return };
    let mut doc = golden_doc();
    doc.clock.targets.get_mut("SYSCLK").unwrap().hz = 96_000_000; // F103 max is 72
    let resolved = validate(&pack, &doc).expect("hard failure");
    assert!(
        resolved.diags.iter().any(|d| d.code == "CLK_UNSAT"),
        "96 MHz must be unsat on F103: {:?}",
        resolved.diags
    );
}

#[test]
fn f103_rejects_pin_conflict() {
    let Some(pack) = load_pack("stm32f1.irpack") else { return };
    let mut doc = golden_doc();
    // Occupy PA9/PA10 with GPIO, then pin-hint USART1 there too.
    doc.gpio.insert(
        "PA9".into(),
        serde_json::from_str(r#"{ "mode": "output" }"#).unwrap(),
    );
    let resolved = validate(&pack, &doc).expect("hard failure");
    assert!(
        resolved
            .diags
            .iter()
            .any(|d| d.code.starts_with("PIN_")),
        "conflict must be diagnosed: {:?}",
        resolved.diags
    );
}

#[test]
fn f103_exti_pc13_resolves_exti15_10_vector() {
    let Some(pack) = load_pack("stm32f1.irpack") else { return };
    let mut doc = golden_doc();
    doc.gpio.insert(
        "PC13".into(),
        serde_json::from_str(
            r#"{ "mode": "exti", "trigger": "falling", "pull": "up", "label": "BTN",
                 "nvic": { "enabled": true, "preemptionPriority": 2 } }"#,
        )
        .unwrap(),
    );
    let resolved = validate(&pack, &doc).expect("hard failure");
    for d in &resolved.diags {
        eprintln!("diag: {:?} {} {} {}", d.severity, d.code, d.path, d.message);
    }
    assert!(!has_errors(&resolved.diags), "exti config must be clean");

    let irq = resolved
        .nvic
        .iter()
        .find(|i| i.irqn == "EXTI15_10_IRQn")
        .expect("PC13 (line 13) must resolve to the shared EXTI15_10 vector");
    assert_eq!(irq.owner, "EXTI13");
    assert_eq!(irq.preemption_priority, 2);
    assert_eq!(irq.sub_priority, 0);
    assert_eq!(irq.handlers, vec!["HAL_GPIO_EXTI_IRQHandler".to_string()]);
    assert_eq!(irq.args, "10,15");
}

#[test]
fn f103_exti_shared_vector_dedups_to_highest_priority() {
    let Some(pack) = load_pack("stm32f1.irpack") else { return };
    let mut doc = golden_doc();
    // PB5 + PB7 both live on EXTI9_5_IRQn; PB7's numerically lower
    // preemption priority must win the single ResolvedIrq.
    for (pad, pri) in [("PB5", 3u32), ("PB7", 1u32)] {
        doc.gpio.insert(
            pad.into(),
            serde_json::from_str(&format!(
                r#"{{ "mode": "exti", "nvic": {{ "enabled": true, "preemptionPriority": {pri} }} }}"#
            ))
            .unwrap(),
        );
    }
    let resolved = validate(&pack, &doc).expect("hard failure");
    assert!(!has_errors(&resolved.diags), "diags: {:?}", resolved.diags);
    let irqs: Vec<_> = resolved
        .nvic
        .iter()
        .filter(|i| i.irqn == "EXTI9_5_IRQn")
        .collect();
    assert_eq!(irqs.len(), 1, "shared vector must dedup: {:?}", resolved.nvic);
    assert_eq!(irqs[0].preemption_priority, 1, "lowest preemption wins");
    assert_eq!(irqs[0].owner, "EXTI7");
}

#[test]
fn determinism_same_input_same_output() {
    let Some(pack) = load_pack("stm32f1.irpack") else { return };
    let doc = golden_doc();
    let a = validate(&pack, &doc).unwrap();
    let b = validate(&pack, &doc).unwrap();
    assert_eq!(format!("{:?}", a.clock), format!("{:?}", b.clock));
    assert_eq!(
        format!("{:?}", a.pin_plan.placements),
        format!("{:?}", b.pin_plan.placements)
    );
}

/// BZ#83533 (F103 remap erratum): PB5's condition `!(SPI1_MOSI & PB6_I2C1_SCL)`
/// forbids SPI1_MOSI *on PB5* together with I2C1_SCL on PB6. Bare terms are
/// pin-local; with SPI1 on its default PA5/6/7 pins the erratum must NOT fire.
/// The global reading rejected every I2C1+SPI1 board (anyshake Explorer being
/// the reference victim — its CubeMX project enables both).
#[test]
fn i2c1_spi1_default_pins_coexist() {
    let Some(pack) = load_pack("stm32f1.irpack") else { return };
    let doc: ConfigDoc = serde_json::from_str(
        r#"{
          "schemaVersion": 1,
          "mcu": { "part": "STM32F103C8Tx" },
          "peripherals": {
            "SPI1": {
              "mode": "Full_Duplex_Master",
              "pins": { "SCK": "PA5", "MISO": "PA6", "MOSI": "PA7" }
            },
            "I2C1": { "mode": "I2C", "pins": { "SCL": "PB6", "SDA": "PB7" } }
          }
        }"#,
    )
    .unwrap();
    let resolved = validate(&pack, &doc).expect("hard failure");
    let exclusions: Vec<_> = resolved
        .diags
        .iter()
        .filter(|d| d.code == "PIN_EXCLUSION")
        .collect();
    assert!(
        exclusions.is_empty(),
        "SPI1 on PA5/6/7 must not trip the PB5 erratum: {exclusions:?}"
    );
    assert!(!has_errors(&resolved.diags), "diags: {:?}", resolved.diags);
}

/// The same erratum must still fire when SPI1_MOSI actually remaps onto PB5.
#[test]
fn spi1_remapped_to_pb5_with_i2c1_fires_exclusion() {
    let Some(pack) = load_pack("stm32f1.irpack") else { return };
    let doc: ConfigDoc = serde_json::from_str(
        r#"{
          "schemaVersion": 1,
          "mcu": { "part": "STM32F103C8Tx" },
          "peripherals": {
            "SPI1": {
              "mode": "Full_Duplex_Master",
              "pins": { "SCK": "PB3", "MISO": "PB4", "MOSI": "PB5" }
            },
            "I2C1": { "mode": "I2C", "pins": { "SCL": "PB6", "SDA": "PB7" } }
          }
        }"#,
    )
    .unwrap();
    let resolved = validate(&pack, &doc).expect("hard failure");
    assert!(
        resolved
            .diags
            .iter()
            .any(|d| d.code == "PIN_EXCLUSION" && d.message.contains("BZ#83533")),
        "remapped MOSI on PB5 + I2C1_SCL on PB6 is the documented erratum: {:?}",
        resolved.diags
    );
}
