export const serialCopy = {
  en: {
    port: "Port",
    baud: "Baud rate",
    selectPort: "Select or enter a port",
    noPorts: "Enter a port path",
    portPresets: "Available serial ports",
    baudPresets: "Common baud rates",
    scan: "Refresh serial ports",
    connect: "Connect",
    disconnect: "Disconnect",
    working: "Working…",
    connected: "Connected",
    disconnected: "Disconnected",
    lines: "lines",
    lineEnding: "Line ending",
    sendPlaceholder: "Type a message to send to the serial port…",
    sendMode: "Send format",
    text: "Text (UTF-8)",
    send: "Send",
    sending: "Sending…",
    sent: "Sent",
    enterSend: "Enter to send · ↑ / ↓ for history",
    ctrlHint: "Send Ctrl+C (0x03), without a line ending",
    readOnlySource: "This TCP/command log is receive-only. Connect a serial port or RTT to send.",
    readOnly: "receive-only",
    noEnding: "No line ending",
    invalidHex: "Enter complete hexadecimal byte pairs, e.g. 01 A0 FF. Spaces are optional.",
    invalidSize: "Send between 1 and 4096 bytes, including the selected line ending.",
    invalid: "Enter a serial port and an integer baud rate between 50 and 12,000,000.",
    empty: "Log monitor",
    emptyHint:
      "Pick a serial port or J-Link RTT and connect to see your board’s output here; logs the agent captures with the log tool show up here too.",
    source: "Log source",
    serial: "Serial",
    rtt: "RTT",
    serialTitle: "Serial: a UART or USB virtual COM port",
    rttTitle: "J-Link RTT: reads the firmware’s RTT channel 0 as text over SWD — no halt, reset or flashing",
    device: "J-Link device",
    devicePlaceholder: "Device, e.g. STM32G473RC",
    deviceFamily: "Exact part (project says {chip})",
    deviceTitle:
      "J-Link device name, up to the flash-size code (STM32G473RC). CubeMX names and ordering codes (STM32G473RCTx, STM32G473RCT6) are shortened for you.",
    speed: "SWD speed (kHz)",
    speedPresets: "Common SWD speeds",
    invalidDevice: "Enter the J-Link device name, e.g. STM32G473RC.",
    familyDevice: "{chip} is a CubeMX family name, not one chip. Enter the exact part, e.g. STM32G473RC.",
    invalidSpeed: "Enter an integer SWD speed between 5 and 50,000 kHz.",
    sendPlaceholderRtt: "Type a message to send to RTT channel 0…",
    connecting: "Connecting…",
    cancel: "Cancel",
  },
  zh: {
    port: "端口",
    baud: "波特率",
    selectPort: "选择或输入端口",
    noPorts: "输入串口路径",
    portPresets: "可用串口",
    baudPresets: "常用波特率",
    scan: "刷新串口列表",
    connect: "连接",
    disconnect: "断开",
    working: "处理中…",
    connected: "已连接",
    disconnected: "未连接",
    lines: "行",
    lineEnding: "换行符",
    sendPlaceholder: "输入要发送到串口的内容…",
    sendMode: "发送格式",
    text: "文本 (UTF-8)",
    send: "发送",
    sending: "发送中…",
    sent: "已发送",
    enterSend: "Enter 发送 · ↑ / ↓ 历史命令",
    ctrlHint: "发送 Ctrl+C (0x03)，不附加换行符",
    readOnlySource: "当前为 TCP/命令日志，仅接收；连接串口或 RTT 后可以发送。",
    readOnly: "只收不发",
    noEnding: "不加换行",
    invalidHex: "请输入完整的十六进制字节，例如 01 A0 FF，可以省略空格。",
    invalidSize: "每次发送 1–4096 字节，包含所选换行符。",
    invalid: "请输入串口，以及 50 到 12,000,000 之间的整数波特率。",
    empty: "日志监视器",
    emptyHint: "选好串口或 RTT 点「连接」，开发板的输出显示在这里；agent 用 log 工具采集的日志也在这里。",
    source: "日志来源",
    serial: "串口",
    rtt: "RTT",
    serialTitle: "串口：UART 或 USB 虚拟串口",
    rttTitle: "J-Link RTT：经 SWD 读固件 RTT 通道 0 的文本，不停核、不复位、不烧录",
    device: "J-Link 器件名",
    devicePlaceholder: "器件名，如 STM32G473RC",
    deviceFamily: "确切型号（工程里是 {chip}）",
    deviceTitle:
      "J-Link 认的器件名，写到 Flash 容量码为止（STM32G473RC）。CubeMX 名与订货号（STM32G473RCTx、STM32G473RCT6）会自动缩短。",
    speed: "SWD 速率 (kHz)",
    speedPresets: "常用 SWD 速率",
    invalidDevice: "请输入 J-Link 器件名，例如 STM32G473RC。",
    familyDevice: "{chip} 是 CubeMX 的芯片家族名，不是一颗确定的芯片；请填确切型号，例如 STM32G473RC。",
    invalidSpeed: "SWD 速率请填 5 到 50000 之间的整数（kHz）。",
    sendPlaceholderRtt: "输入要发送到 RTT 通道 0 的内容…",
    connecting: "正在连接…",
    cancel: "取消",
  },
} as const
