export const serialCopy = {
  en: {
    port: "Port",
    baud: "Baud rate",
    selectPort: "Select or enter a port",
    noPorts: "Enter a port path",
    portPresets: "Available serial ports",
    baudPresets: "Common baud rates",
    scan: "Refresh serial ports",
    format: "8 data bits · no parity · 1 stop bit · no flow control",
    connect: "Connect",
    disconnect: "Disconnect",
    working: "Working…",
    connected: "Connected",
    disconnected: "Disconnected",
    readyHint: "Select a port and baud rate to start monitoring",
    lines: "lines",
    lineEnding: "Line ending",
    sendPlaceholder: "Type a message to send to the serial port…",
    sendMode: "Send format",
    text: "Text (UTF-8)",
    send: "Send",
    sending: "Sending…",
    sent: "Sent",
    enterSend: "Enter to send · ↑ / ↓ for history",
    ctrlHint: "Send Ctrl+C (0x03), without a line ending",
    readOnlySource: "This TCP/command log is receive-only. Connect a serial port to send.",
    invalidHex: "Enter complete hexadecimal byte pairs, e.g. 01 A0 FF. Spaces are optional.",
    invalidSize: "Send between 1 and 4096 bytes, including the selected line ending.",
    invalid: "Enter a serial port and an integer baud rate between 50 and 12,000,000.",
    empty: "Serial monitor",
    emptyHint: "Connect to see your board’s output. Send commands below; no agent or model setup needed.",
  },
  zh: {
    port: "端口",
    baud: "波特率",
    selectPort: "选择或输入端口",
    noPorts: "输入串口路径",
    portPresets: "可用串口",
    baudPresets: "常用波特率",
    scan: "刷新串口列表",
    format: "8 数据位 · 无校验 · 1 停止位 · 无流控",
    connect: "连接",
    disconnect: "断开",
    working: "处理中…",
    connected: "已连接",
    disconnected: "未连接",
    readyHint: "选择端口和波特率，开始监听",
    lines: "行",
    lineEnding: "换行符",
    sendPlaceholder: "输入要发送到串口的内容…",
    sendMode: "发送格式",
    text: "文本 (UTF-8)",
    send: "发送",
    sending: "发送中…",
    sent: "已发送",
    enterSend: "Enter 发送 · ↑ / ↓ 历史命令",
    ctrlHint: "发送 Ctrl+C (0x03)，不附加换行符",
    readOnlySource: "当前为 TCP/命令日志，仅接收；连接串口后可以发送。",
    invalidHex: "请输入完整的十六进制字节，例如 01 A0 FF，可以省略空格。",
    invalidSize: "每次发送 1–4096 字节，包含所选换行符。",
    invalid: "请输入串口，以及 50 到 12,000,000 之间的整数波特率。",
    empty: "串口监视器",
    emptyHint: "连接后查看开发板输出，在下方输入并发送命令。无需 Agent 或模型配置。",
  },
} as const
