import { readFileSync, writeFileSync } from "node:fs"
import path from "node:path"

const colors = readFileSync(path.join(import.meta.dirname, "colors.txt"), "utf8")

const variables = []
for (const line of colors.split("\n")) {
  if (!line.trim()) continue
  const [variable] = line.trim().split(":")
  const name = variable!.trim().substring(2)
  variables.push(`--color-${name}: var(--${name});`)
}

const output = `
/* Generated by script/tailwind.ts */
/* Do not edit this file manually */

@theme {
  --color-*: initial;
  ${variables.join("\n  ")}
}
`

writeFileSync(path.join(import.meta.dirname, "..", "src", "styles", "tailwind", "colors.css"), output.trim())
